name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ ci-test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: centos
    env: 
      SYNOPKG_DSM_VERSION_MAJOR: 6
      SYNOPKG_PKGDEST: /var/packages/adoptopenjdk/target/
      SYNOPKG_PKGNAME: adoptopenjdk
      JAVA_VERSION_8: false
      JAVA_VERSION_11: true
      JAVA_VERSION_15: false
      JAVA_IMAGE_TYPE: jre
      JVM_IMPL: openj9

    steps:
      - uses: actions/checkout@v2
      
      - name: pre-init-sys
        run: |
          yum install -y jq
          
      - name: pre-init-env
        run: |
          mkdir -p $SYNOPKG_PKGDEST

      - name: run installer
        run: |
          . scripts/installer.sh
          preinst
          postinst
          
      - name: run start-stop-status
        run: |
          ls -la /etc
          ls -la /root
          . scripts/start-stop-status.sh start
          . scripts/start-stop-status.sh stop
          . scripts/start-stop-status.sh status
          . scripts/start-stop-status.sh log
          cat "${SYNOPKG_PKGDEST}"/output.log
          
      - name: run upgrade
        run: |
          . scripts/installer.sh
          preupgrade
          postupgrade
                
      - name: run uninstaller
        run: |
          . scripts/installer.sh
          preuninst
          postuninst
          
      - name: run UI generator
        env:
          SYNOPKG_TEMP_LOGFILE: ../install_uifile_temp
        run: |
          cd WIZARD_UIFILES
          ./install_uifile.sh
          HAS_ERROR_LINES="$(grep -c JAVA_UI_INSTALL_ERROR $SYNOPKG_TEMP_LOGFILE)" || true
          if [ "$HAS_ERROR_LINES" -ne 0 ]; then
            exit 12
          fi
          HAS_JAVA_LINES="$(grep -c JAVA_VERSION_ $SYNOPKG_TEMP_LOGFILE)" || true
          if [ "$HAS_JAVA_LINES" -lt 3 ]; then
            exit 23
          fi
          
      - name: run UI fallback generator
        env:
          SYNOPKG_TEMP_LOGFILE: ../install_uifile_temp
        run: |
          cd WIZARD_UIFILES
          sed -e 's/\"step_title\":/;/g' ./install_uifile.sh > ./tmpfile && mv ./tmpfile ./install_uifile.sh
          chmod 755 ./install_uifile.sh
          ./install_uifile.sh
          HAS_ERROR_LINES="$(grep -c JAVA_UI_INSTALL_ERROR $SYNOPKG_TEMP_LOGFILE)" || true
          if [ "$HAS_ERROR_LINES" -ne 1 ]; then
            exit 12
          fi

